name: recomendador-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip:
      - mlflow<2.17
      - azureml-mlflow
      - pandas
      - scikit-learn
      - sentence-transformers
      - torch
      - transformers
